config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  namespace :admin do
    resources :organizations, only: [ :index, :show ]
    resources :users, only: [ :index, :show ]
  end

  namespace :org do
    resources :users
    resources :organizations
  end
  get '/dashboard', to: 'org/users#dashboard'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
class Organization < ApplicationRecord

  has_many :user_organizations
  has_many :users, through: :user_organizations

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :contact_name, presence: true
  validates :contact_email, presence: true
  validates :contact_phone, presence: true
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :postal_code, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable, :lockable

  has_many :user_organizations
  has_many :organizations, through: :user_organizations do
    def manager
      where("user_organizations.administrator = true or user_organizations.trial_secretary = true")
    end
    def handler
      where("user_organizations.handler = true")
    end
  end

  validates :first_name, presence: true
  validates :last_name, presence: true

  def organization_manager?
    user_organizations.manager.any?
  end

  def handler?
    user_organizations.handler.any?
  end
end

app/models/user_organization.rb
class UserOrganization < ApplicationRecord

  belongs_to :user
  belongs_to :organization

  delegate :name, prefix: true, to: :organization
  delegate :first_name, :last_name, prefix: true, to: :user

  scope :manager, -> { where("administrator = true or trial_secretary = true") }
  scope :handler, -> { where(handler: true) }

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < AdminController

  def index
    @organization_presenters = Organization.includes(user_organizations: :user).order(:name).inject([]) { |a, o| a << OrganizationPresenter.new(o); a }
  end

  def show
    @organization_presenter = OrganizationPresenter.new(Organization.find(params[:id]))
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def index
    @user_presenters = User.includes(user_organizations: :organization).order(:last_name, :first_name).inject([]) { |a, u| a << UserPresenter.new(u); a }
  end

  def show
    user = User.includes(:user_organizations).where(id: params[:id]).first
    @user_presenter = UserPresenter.new(user)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    return dashboard_path if resource.is_a? User
    super
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/org/organizations_controller.rb
class Org::OrganizationsController < OrgController

  before_action :load_organization, only: [ :show, :edit, :update, :destroy ]

  def index
    @organization_presenters = current_user.organizations.map { |o| OrganizationPresenter.new(o) }
  end

  def show
    @organization_presenter = OrganizationPresenter.new(@organization)
  end

  def edit
  end

  private

    def load_organization
      @organization = Organization.find(params[:id])
    end

end

app/controllers/org/users_controller.rb
class Org::UsersController < OrgController

  def dashboard
    @user_presenter = UserPresenter.new(current_user)
  end

  def show
    @user_presenter = UserPresenter.new(User.find(params[:id]))
  end

end

app/controllers/org_controller.rb
class OrgController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title) { page_title }
  end

  def title_html(html_data)
    content_for(:title_html) { html_data.html_safe }
  end

  def small_add_button(path, text='ADD')
    link_to text, path, class: 'btn btn-small btn-green'
  end

  def small_edit_button(path, text='EDIT')
    link_to text, path, class: 'btn btn-small btn-yellow'
  end

  def small_delete_button(path, text='DELETE')
    link_to text, path, class: 'btn btn-small btn-red', method: :delete, data: { confirm: 'Are you sure you want to delete this item?' }
  end


end

app/views/admin/organizations/index.html.slim
- title 'Organizations'

- if @organization_presenters.any?
  table.table.table-striped
    thead
      tr
        th Name
        th Members
        th Street
        th City
        th State
        th Postal Code
        th Contact Name
        th Contact Email
        th Contact Phone
        th Create Date
    tbody
      - @organization_presenters.each do |op|
        tr
          td= link_to op.name, admin_organization_path(op.id)
          td
            - op.user_organization_presenters.each do |uop|
              = link_to uop.user_name_with_membership, admin_user_path(uop.user_id)
              br
          td= op.street
          td= op.city
          td= op.state
          td= op.postal_code
          td= op.contact_name
          td= op.contact_email
          td= op.contact_phone
          td= op.create_date

- else
  p No organizations exist yet.

app/views/admin/organizations/show.html.slim
- title @organization_presenter.name

dl
  dt Street
  dd= @organization_presenter.street
  dt City
  dd= @organization_presenter.city
  dt State
  dd= @organization_presenter.state
  dt Postal Code
  dd= @organization_presenter.postal_code
  dt Contact Name
  dd= @organization_presenter.contact_name
  dt Contact Email
  dd= @organization_presenter.contact_email
  dt Contact Phone
  dd= @organization_presenter.contact_phone
  dt Create Date
  dd= @organization_presenter.create_date

h3 Members
table.table.table-striped
  thead
    tr
      th Full Name
      th Membership
  tbody
    - @organization_presenter.user_organization_presenters.each do |uop|
      tr
        td= link_to uop.user_full_name, admin_user_path(uop.user_id)
        td= uop.membership

app/views/admin/users/index.html.slim
- title 'Users'

- if @user_presenters.any?
  table.table.table-striped
    thead
      tr
        th Full Name
        th Email
        th Organizations
        th Create Date
    tbody
      - @user_presenters.each do |up|
        tr
          td= link_to up.full_name, admin_user_path(up.id)
          td= up.email
          td
            - up.user_organization_presenters.each do |uop|
              = link_to uop.organization_name_with_membership, admin_organization_path(uop.organization_id)
              br
          td= up.create_date

- else
  p No users exist yet.

app/views/admin/users/show.html.slim
- title @user_presenter.full_name

dl
  dt Email
  dd= @user_presenter.email
  dt Sign In Count
  dd= @user_presenter.sign_in_count
  dt Current Sign In At
  dd= @user_presenter.current_sign_in_at
  dt Last Sign In At
  dd= @user_presenter.last_sign_in_at
  dt Current Sign In IP
  dd= @user_presenter.current_sign_in_ip
  dt Last Sign In IP
  dd= @user_presenter.last_sign_in_ip
  dt Confirmed?
  dd= @user_presenter.confirmed?
  dt Failed Attempts
  dd= @user_presenter.failed_attempts
  dt Locked?
  dd= @user_presenter.locked?

h3 Organizations
table.table.table-striped
  thead
    tr
      th Name
      th Membership
  tbody
    - @user_presenter.user_organization_presenters.each do |uop|
      tr
        td= link_to uop.organization_name, admin_organization_path(uop.organization_id)
        td= uop.membership

app/views/layouts/_navigation.html.slim
.navbar.navbar-default.navbar-fixed-top role='navigation'
  .container
    .navbar-header
      button.navbar-toggle data-toggle='collapse' data-target='.navbar-collapse'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Trial Manager', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav.pull-right
        - if current_user.present?
          li.dropdown
            a.dropdown-toggle href='#' data-toggle='dropdown'
              | Menu
              b.caret
            ul.dropdown-menu
              li= link_to 'Dashboard', dashboard_path
              li= link_to('Organizations', org_organizations_path) if current_user.organization_manager?
        - if current_admin.present?
          li.dropdown
            a.dropdown-toggle href='#' data-toggle='dropdown'
              | Admin
              b.caret
            ul.dropdown-menu
              li= link_to('Organizations', admin_organizations_path)
              li= link_to('Users', admin_users_path)
        li= link_to('Sign In', new_user_session_path) unless user_signed_in?
        li= link_to('Sign Out', destroy_user_session_path, method: :delete) if user_signed_in?

app/views/layouts/application.html.slim
doctype html
html
  head
    title Trial Manager
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    #wrap
      = render '/layouts/navigation'

      .container.content
        - if content_for?(:title) || content_for?(:title_html)
          h1
            = yield(:title)
            = yield(:title_html)

        - if notice
          p.notice= notice

        - if alert
          p.alert= alert

        = yield

      #push

    #footer
      .container
        div.right
          - if admin_signed_in?
            = link_to('Admin Sign Out', destroy_admin_session_path, method: :delete)
          - else
            = link_to('Admin Access', new_admin_session_path)

app/views/org/organizations/index.html.slim
- title 'Organizations'

- if @organization_presenters.any?
  table.table.table-striped
    thead
      tr
        th Name
        th Members
        th Street
        th City
        th State
        th Postal Code
        th Contact Name
        th Contact Email
        th Contact Phone
        th Create Date
    tbody
      - @organization_presenters.each do |op|
        tr
          td= link_to op.name, org_organization_path(op.id)
          td
            - op.user_organization_presenters.each do |uop|
              = link_to uop.user_name_with_membership, org_user_path(uop.user_id)
              br
          td= op.street
          td= op.city
          td= op.state
          td= op.postal_code
          td= op.contact_name
          td= op.contact_email
          td= op.contact_phone
          td= op.create_date

app/views/org/organizations/show.html.slim
- title_html @organization_presenter.name + small_edit_button(edit_org_organization_path(@organization))

dl
  dt Street
  dd= @organization_presenter.street
  dt City
  dd= @organization_presenter.city
  dt State
  dd= @organization_presenter.state
  dt Postal Code
  dd= @organization_presenter.postal_code
  dt Contact Name
  dd= @organization_presenter.contact_name
  dt Contact Email
  dd= @organization_presenter.contact_email
  dt Contact Phone
  dd= @organization_presenter.contact_phone
  dt Create Date
  dd= @organization_presenter.create_date

h3 Members
table.table.table-striped
  thead
    tr
      th Full Name
      th Membership
  tbody
    - @organization_presenter.user_organization_presenters.each do |uop|
      tr
        td= link_to uop.user_full_name, admin_user_path(uop.user_id)
        td= uop.membership

app/views/org/users/dashboard.html.slim
- title 'Dashboard'

h2 Trials

app/views/org/users/show.html.slim
- title @user_presenter.full_name

dl
  dt Email
  dd= @user_presenter.email